apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-amd64
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx-amd64
  template:
    metadata:
      labels:
        app: nginx-amd64
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: nginx-amd64
          image: nginxdemos/hello
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "100m"
